### ISSUE TITLE
bug/feat fiducials and diodes automatically added to the bar

### ISSUE THREAD

**Issue by BijalBPatel** [NSLS-II-SST/rsoxs#2]
Follow-up on an a couple of notes from 2023-1 beamtime:

1. Autogenerated samples 'diode', 'AF1_front', and 'AF2_front' generated errors due to missing columns for 'proposal_id' and 'bar name'.
2. We had to add a manual grazing diode as well
3. Somehow we didn't get positions for AF2, which we found out the next day. We could add a check that makes sure all samples have position values at the end of image_bar, so that this is caught automatically before we do find_fiducials() when we have beam.

Relevant code is: https://github.com/NSLS-II-SST/rsoxs/blob/5d581a9a0783db6ace98f095419034bcd24b3708/rsoxs/Functions/alignment.py#L1009-L1044 

While we are at it, here are some related suggestions:
4. Expand scope of 'diode' replacement string to cover caps versions 'Diode'
5. Update documentation on spreadsheet instructions to tell users not to enter diodes
6. Automatically sort the bar by sample position prior to clicking images

**Comment by EliotGann** [comment]
I think this is fixed with the new nexafs_step branch which I'd like to merge today.

**Comment by EliotGann** [comment]
to update, this is not all fixed, and there is still unexpected behavior

**Comment by PriyankaKetkarBNL** [comment]
Addressed by PR #9
